FROM hpccsystems/linux:el6_hpcc5
MAINTAINER Xiaoming Wang <xiaoming.wang@lexisnexis.com>
RUN yum update -y 
RUN wget <URL_BASE>/<HPCC_IMAGE>
RUN groupadd hpcc
RUN useradd -s /bin/bash -r -m -d /home/hpcc -g hpcc -c "hpcc Runtime User" hpcc
RUN yum install --nogpgcheck -y <HPCC_IMAGE>
EXPOSE 8010

