FROM centos:7
MAINTAINER Xiaoming Wang <xiaoming.wang@lexisnexis.com>
RUN yum update -y 
RUN yum install -y gcc-c++
RUN yum install -y boost-regex openldap libicu m4 libtool
RUN yum install -y libxslt libxml2 openssh-server openssh-clients 
RUN yum install -y expect libarchive rsync apr apr-util zip tbb
