FROM hpccsystems/linux:el7_hpcc5
MAINTAINER Xiaoming Wang <xiaoming.wang@lexisnexis.com>
RUN yum update -y 
RUN yum install -y  net-tools which
RUN chmod u+s $(which ping)
RUN wget <URL_BASE>/<HPCC_IMAGE>
RUN yum install --nogpgcheck -y <HPCC_IMAGE>
EXPOSE 8010 8002 8015 9876
ADD run_master.sh /tmp/
RUN chmod +x /tmp/run_master.sh
RUN mkdir -p /var/run/sshd
CMD ["bash", "-c",  "/usr/sbin/sshd -D"]
